### ISSUE TITLE
Question navigation button is inconsistent

### ISSUE THREAD

**Issue by Neelesh2512** [project-sunbird/sunbird-quml-player#261]
# Description
The question navigation button at the top right is inconsistent. It only shows up when we click on the 1st question.

# How to test
1. Click on question A and then navigate to b -> c -> d by clicking the button
![image](https://user-images.githubusercontent.com/77741561/171263686-c3cc8f20-aaa9-47be-915e-14880110d11a.png)

2. Now click on question D, navigation buttons will not show up on D, C, B, and even on A.
![image](https://user-images.githubusercontent.com/77741561/171263994-e03280d2-cf0d-45d3-b7d8-800cc5897ce6.png)

**Comment by pallakartheekreddy** [comment]
@Neelesh2512 Can you please initiate this discussion in the [inQuiry](https://github.com/Sunbird-inQuiry/Community/discussions) building block forums. as we all are actively working on inQuiry forums.
**Note**: We are working on the code movement of the QuML player from `project-sunbird` to `Sunbird-inQuiry`
